<?php

require_once '../Boundio.php';

/**
 * Test class for Boundio.
 * Generated by PHPUnit on 2012-03-14 at 19:16:10.
 */
class BoundioTest extends PHPUnit_Framework_TestCase
{

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		Boundio::configure('userSerialId', '');
		Boundio::configure('appId', '');
		Boundio::configure('authKey', '');
	}

	/**
	 * @todo Implement testCall().
	 */
	public function testCall()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStatus().
	 */
	public function testStatus()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFile().
	 */
	public function testFile()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}
}
?>
