<?php

require_once dirname(__FILE__). '/../Boundio.php';

/**
 * Test class for Boundio.
 * Generated by PHPUnit on 2012-03-14 at 19:16:10.
 */
class BoundioTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		/*
		Boundio::configure('userSerialId', '');
		Boundio::configure('appId', '');
		Boundio::configure('authKey', '');
		*/
	}

	/**
	 * @todo Implement testCall().
	 */
	public function testCall()
	{
		// Validation Error
		// phone number
		$this->assertEquals(false, Boundio::call('1234', array()));
		$this->assertEquals(false, Boundio::call('test', array()));
		
		// casts
		$this->assertEquals(false, Boundio::call('0123456789', array('file(000001)', 'silent()', 'num(0)', 'test')));
		
		// create mock to be fake api call function
		$mock = $this->getMock('Boundio', array('_execute'));
		$mock::staticExpects($this->any())
			->method('_execute')
			->will($this->returnValue('{"success":"true","_id":"1234"}'));
		
		// call success
		$this->assertEquals(array('success' => "true", '_id' => '1234'), $mock::call('0123456789', array('file(000001)')));
	}

	/**
	 * @todo Implement testStatus().
	 */
	public function testStatus()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFile().
	 */
	public function testFile()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		  'This test has not been implemented yet.'
		);
	}
}
?>
